/** @type {import('next').NextConfig} */
const nextConfig = {
  // GitHub Pages serves files, not a Node server, so the whole site is
  // pre-rendered to `out/`. Everything below follows from that.
  output: 'export',

  // `next/image`'s optimizer needs that server. With `output: export` it cannot
  // run, so images would be served exactly as authored — which is the bug this
  // rebuild started with. Screenshots go through <ResponsiveImage> instead,
  // which reads the AVIF/WebP variants tools/optimize_images.py wrote and the
  // 20px placeholder that ships in the markup.
  images: { unoptimized: true },

  // Pages has no rewrite layer, so every route is a directory with an
  // index.html. Without this, /de/features would 404 unless the visitor typed
  // the .html themselves.
  trailingSlash: true,

  // The old site is generated by build.py into site/; this one builds to out/.
  // Both exist until the switch, and neither may pick up the other's tree.
  distDir: '.next',
};

export default nextConfig;
